BEGIN;
INSERT INTO noteful_notes (title, content, folder_id)
VALUES
  ('Persians', 'White cats with fluffy fur.', 1),
  ('Blue Russians', 'Dark blue cats with short fur.', 1),
  ('Ragdolls', 'All colors but act like a doll.', 1),
  ('Chihuahua', 'Tiny dogs kept as pets.', 2),
  ('Husky', 'Big dogs with thick wiry coats great for winter.', 2),
  ('Shelties', 'Smart medium dogs who like to herd.', 2),
  ('Finchs', 'Yellow wild noisy bird.', 3),
  ('Crows', 'Big black birds.', 3),
  ('Parrots', 'Colorful birds that can be taught to talk.', 3),
  ('Hamsters', 'Pudgy animals that look like a ball.', 4),
  ('Guinea Pigs', 'Bigger versions of hamsters.', 4),
  ('Mice', 'Small creatures that can get everywhere.', 4),
  ('Arabians', 'Strong powerful animals.', 5),
  ('Thoroughbreds', 'Great animals for racing.', 5),
  ('Clydesdales', 'Large heavy animals, used for pulling, such as fire engines.', 5),
  ('Regular', 'Light brown with black stripes.', 6),
  ('Dark', 'Switched colors of the regulars.', 6),
  ('Albino', 'All white versions.', 6),
  ('Dwarf', 'Tiny cute animals.', 7),
  ('Lop ears', 'Long ears, big and floppy ears.', 7),
  ('Lion Haired', 'Hair like a mane around its face.', 7),
  ('Chameleon', 'Changes colors to blend with environment.', 8),
  ('Salamandar', 'Can lose tail if pulled and grow back.', 8),
  ('Bearded Dragons', 'Calm animals that look like statues.', 8),
  ('Cichlids', 'Very agressive and large fish, not friendly.', 9),
  ('Tetras', 'Easily fish to keep alive and hardy.', 9),
  ('Goldfish', 'Most common, and quite dirty.', 9),
  ('Raccoons', 'Striped bandits, make sure outside ones do not get attracted to yours.', 10),
  ('Chinchilla', 'Animal with softest fur ever.', 10),
  ('Foxes', 'Very smart creatures that are like dogs.', 10);
COMMIT;